apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    function: webserver
spec:
  containers:
  - name: httpd
    image: docker.io/httpd:latest
    ports:
    - containerPort: 80

    resources:
      limits:
        cpu: 250m 
        memory: 512Mi
        ephemeral-storage: 10Mi

    livenessProbe:
      httpGet:
        path: /polls/
        port: 8000