apiVersion: v1
kind: Pod
metadata:
  name: mysite
  labels:
    function: webserver
spec:
  containers:
  - name: httpd
    image: ghcr.io/angelo-segretto-iv/cis-92:milestone-4.10
    ports:
    - containerPort: 80

    resources:
      limits:
        cpu: 250m 
        memory: 512Mi
        ephemeral-storage: 10Mi

    livenessProbe:
      httpGet:
        path: /polls/
        port: 80

    env: 
    - name: SECRET_KEY
      value: anything
    - name: PORT
      value: '80'
