apiVersion: v1
kind: Pod
metadata:
  name: mysite
  labels:
    function: webserver
spec:
  containers:
  - name: httpd
    image: ghcr.io/angelo-segretto-iv/cis-92:milestone-5.2
    ports:
    - containerPort: 80

    resources:
      limits:
        cpu: 250m 
        memory: 512Mi
        ephemeral-storage: 10Mi

    livenessProbe:
      httpGet:
        path: /polls/
        port: 80

    env: 
    - name: SECRET_KEY
      value: anything
    - name: PORT
      value: '80'

    env:
    - name: DB_ENGINE
      value: "postgres"
    - name: DB_NAME
      value: "django"
    - name: DB_USER
      value: "django"
    - name: DB_PASSWORD
      value: "django"
    - name: DB_HOST
      value: "34.133.45.132"
